/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package budgetbuddy;

/**
 *
 * @author yielc
 */
public class addExpenses extends javax.swing.JFrame {

    /**
     * Creates new form addExpenses
     */
    public addExpenses() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        categoryLabel = new javax.swing.JLabel();
        categoryLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        foodsAndDrinks = new javax.swing.JRadioButton();
        transportation = new javax.swing.JRadioButton();
        utilities = new javax.swing.JRadioButton();
        schoolOrWorkProjects = new javax.swing.JRadioButton();
        shoppingOrPersonalNeeds = new javax.swing.JRadioButton();
        healthAndHygiene = new javax.swing.JRadioButton();
        entertainmentAndLeisure = new javax.swing.JRadioButton();
        savingsOrInvestments = new javax.swing.JRadioButton();
        debtsOrLoans = new javax.swing.JRadioButton();
        subscriptions = new javax.swing.JRadioButton();
        householdItems = new javax.swing.JRadioButton();
        miscellaneousOrOthers = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        pesoSign = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addExpenseButton = new javax.swing.JButton();
        monthDropdown = new javax.swing.JComboBox<>();
        monthLabel = new javax.swing.JLabel();
        dayLabel = new javax.swing.JLabel();
        dayTextField = new javax.swing.JTextField();
        yearLabel = new javax.swing.JLabel();
        yearTextField = new javax.swing.JTextField();
        decimalPoint = new javax.swing.JLabel();
        centTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(106, 212, 177));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 151));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brand.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 28, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        categoryLabel.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        categoryLabel.setForeground(new java.awt.Color(31, 60, 136));
        categoryLabel.setText("CATEGORY:");
        jPanel2.add(categoryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 18, 183, 30));

        categoryLabel1.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        categoryLabel1.setForeground(new java.awt.Color(31, 60, 136));
        categoryLabel1.setText("NOTES:");
        jPanel2.add(categoryLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 228, 175, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 350, 80));

        foodsAndDrinks.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        foodsAndDrinks.setForeground(new java.awt.Color(31, 60, 136));
        foodsAndDrinks.setText("Food & Drinks");
        jPanel2.add(foodsAndDrinks, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 54, 183, -1));

        transportation.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        transportation.setForeground(new java.awt.Color(31, 60, 136));
        transportation.setText("Transportation");
        jPanel2.add(transportation, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 83, 183, -1));

        utilities.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        utilities.setForeground(new java.awt.Color(31, 60, 136));
        utilities.setText("Utilities");
        jPanel2.add(utilities, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 112, 183, -1));

        schoolOrWorkProjects.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        schoolOrWorkProjects.setForeground(new java.awt.Color(31, 60, 136));
        schoolOrWorkProjects.setText("School/Work Projects");
        jPanel2.add(schoolOrWorkProjects, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 141, 183, -1));

        shoppingOrPersonalNeeds.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        shoppingOrPersonalNeeds.setForeground(new java.awt.Color(31, 60, 136));
        shoppingOrPersonalNeeds.setText("Shopping/Personal Needs");
        jPanel2.add(shoppingOrPersonalNeeds, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 170, -1, -1));

        healthAndHygiene.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        healthAndHygiene.setForeground(new java.awt.Color(31, 60, 136));
        healthAndHygiene.setText("Health & Hygiene");
        jPanel2.add(healthAndHygiene, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 199, 183, -1));

        entertainmentAndLeisure.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        entertainmentAndLeisure.setForeground(new java.awt.Color(31, 60, 136));
        entertainmentAndLeisure.setText("Entertainment & Leisure");
        jPanel2.add(entertainmentAndLeisure, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 54, 175, -1));

        savingsOrInvestments.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        savingsOrInvestments.setForeground(new java.awt.Color(31, 60, 136));
        savingsOrInvestments.setText("Savings/Investments");
        jPanel2.add(savingsOrInvestments, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 83, 175, -1));

        debtsOrLoans.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        debtsOrLoans.setForeground(new java.awt.Color(31, 60, 136));
        debtsOrLoans.setText("Debts/Loans");
        jPanel2.add(debtsOrLoans, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 112, 175, -1));

        subscriptions.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        subscriptions.setForeground(new java.awt.Color(31, 60, 136));
        subscriptions.setText("Subscriptions");
        jPanel2.add(subscriptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 141, 175, -1));

        householdItems.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        householdItems.setForeground(new java.awt.Color(31, 60, 136));
        householdItems.setText("Household Items");
        jPanel2.add(householdItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 170, 175, -1));

        miscellaneousOrOthers.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        miscellaneousOrOthers.setForeground(new java.awt.Color(31, 60, 136));
        miscellaneousOrOthers.setText("Miscellaneous/Others");
        jPanel2.add(miscellaneousOrOthers, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 199, 175, -1));

        jLabel3.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(31, 60, 136));
        jLabel3.setText("AMOUNT:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 140, 20));

        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });
        jPanel2.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 110, 30));

        pesoSign.setText("  ₱  ");
        jPanel2.add(pesoSign, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 20, 30));

        jLabel4.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(31, 60, 136));
        jLabel4.setText("DATE:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 120, 30));

        addExpenseButton.setBackground(new java.awt.Color(106, 212, 177));
        addExpenseButton.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        addExpenseButton.setForeground(new java.awt.Color(31, 60, 136));
        addExpenseButton.setText("ADD");
        jPanel2.add(addExpenseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 100, 40));

        monthDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        monthDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthDropdownActionPerformed(evt);
            }
        });
        jPanel2.add(monthDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, -1, -1));

        monthLabel.setText("MONTH: ");
        jPanel2.add(monthLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 136, -1, 30));

        dayLabel.setText("DAY: ");
        jPanel2.add(dayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, -1, 20));

        dayTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(dayTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 30, -1));

        yearLabel.setText("YEAR:");
        jPanel2.add(yearLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, -1, 20));
        jPanel2.add(yearTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 180, 80, -1));

        decimalPoint.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        decimalPoint.setText(".");
        jPanel2.add(decimalPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 20, 30));

        centTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                centTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(centTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountActionPerformed

    private void monthDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthDropdownActionPerformed

    private void dayTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayTextFieldActionPerformed

    private void centTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_centTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_centTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addExpenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addExpenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addExpenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addExpenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addExpenses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addExpenseButton;
    private javax.swing.JTextField amount;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JLabel categoryLabel1;
    private javax.swing.JTextField centTextField;
    private javax.swing.JLabel dayLabel;
    private javax.swing.JTextField dayTextField;
    private javax.swing.JRadioButton debtsOrLoans;
    private javax.swing.JLabel decimalPoint;
    private javax.swing.JRadioButton entertainmentAndLeisure;
    private javax.swing.JRadioButton foodsAndDrinks;
    private javax.swing.JRadioButton healthAndHygiene;
    private javax.swing.JRadioButton householdItems;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton miscellaneousOrOthers;
    private javax.swing.JComboBox<String> monthDropdown;
    private javax.swing.JLabel monthLabel;
    private javax.swing.JLabel pesoSign;
    private javax.swing.JRadioButton savingsOrInvestments;
    private javax.swing.JRadioButton schoolOrWorkProjects;
    private javax.swing.JRadioButton shoppingOrPersonalNeeds;
    private javax.swing.JRadioButton subscriptions;
    private javax.swing.JRadioButton transportation;
    private javax.swing.JRadioButton utilities;
    private javax.swing.JLabel yearLabel;
    private javax.swing.JTextField yearTextField;
    // End of variables declaration//GEN-END:variables
}
